// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhuzaulzdcxromugmeuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodXphdWx6ZGN4cm9tdWdtZXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTk1MzQsImV4cCI6MjA2NDU5NTUzNH0.4dYYD33KAEM1D1qsNU7rX_5zKqn1sxK9UrCaNCosRUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
